name = "ChartParsers"
uuid = "de988000-0167-11e9-3115-2b7bbce15f76"
authors = ["Robin Deits <robin.deits@gmail.com>"]
version = "0.0.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
